### ISSUE TITLE
【需求建议】增加标签和issues入口

### ISSUE THREAD

**Issue by jikeytang** [hstarorg/any-mock#2]
整体上满足我日常功能开发接口数据的需求，准备推广到团队中使用。但在使用当中也不免有更大的需求，为了使产品更健壮，让更多的人使用，简单列了几点，供开发时参考：
1. 建议下次更新时增加【标签】功能，分类是解决纵向信息查询或分类的方法，但级别类下面又有相似的功能，所以可以用标签来纵向列出来。比如：级别只能是业务相关的，技术相关的可以用标签来建立链接。

2. http://mock.hstar.org  中Feedback中可以有一个入口链接到issues上。
3. 在APIList模块中，点击List中Name字段期望能够直接进入详情，就是show detail，增加操作上的易用性。
4. 在Add APIResponse Body中建议增加增加模板支持，减少人工输入，或者支持团队指定模板为团队保证团队数据格式一致。

**Comment by hstarorg** [comment]
如果推广到团队，建议私有部署。这边的完全性做得不够高，服务器也比较垃圾。

**Comment by hstarorg** [comment]
功能性需求，会尽快实现。感谢反馈。

**Comment by hstarorg** [comment]
0.1.1 将会实现2,3。

**Comment by hstarorg** [comment]
转移第1点到：https://github.com/hstarorg/any-mock/issues/4
转移第4点到：https://github.com/hstarorg/any-mock/issues/5
